#! /bin/sh

./configure -with-nethttpd -enable-gtk2 -enable-zip -enable-pcre \
	-enable-gnutls -enable-gssapi \
	-enable-tcl -equeue-tcl-defs -I/usr/include/tcl8.6 -equeue-tcl-libs -ltcl8.6 \
	-enable-apache -apxs /usr/bin/apxs2 -apache /usr/sbin/apache2 \
	"$@"

