TOP_DIR=../..

PRE = 1
PKGNAME = nettls_gnutls
GENERATE = META nettls_gnutls_bindings.ml

CLEAN_LIST += netsys_gnutls_bindings.ml \
              netsys_gnutls_bindings.mli \
              netsys_gnutls_bindings_stubs.c \
              config.log \
              config.h \
              config_checks.sh


include $(TOP_DIR)/Makefile.rules

