TOP_DIR=../..

include $(TOP_DIR)/Makefile.conf

CPPO_VERSION = 0.9.4
GENERATE = cppo_lexer.ml cppo_parser.ml cppo_version.ml

cppo_version.ml:
	echo 'let cppo_version = "$(CPPO_VERSION)"' > cppo_version.ml

include $(TOP_DIR)/Makefile.rules
include depend

