# -*- makefile-mode -*-
TOP_DIR=../..

include $(TOP_DIR)/Makefile.conf

PRE = 1
PKGNAME = netstring-pcre
GENERATE = netstring_pcre.mli netstring_pcre.ml META
#PACKLIST = netstring-pcre-packlist
#INSTALL_EXTRA = netstring-pcre-packlist

pp = $(CPPO) $(REGEXP_DEFS) $(PP_BYTES) $(PP_DEPRECATED)

include $(TOP_DIR)/Makefile.rules

CLEAN_LIST += $(GENERATE)

netstring_pcre.mli: netstring_pcre.mlip
	$(pp) netstring_pcre.mlip > netstring_pcre.mli || \
	      rm -f netstring_pcre.mli

netstring_pcre.ml: netstring_pcre.mlp
	$(pp) netstring_pcre.mlp > netstring_pcre.ml || \
	      rm -f netstring_pcre.ml
