TOP_DIR=../..

include $(TOP_DIR)/Makefile.conf

PKGNAME = netstring-pcre
OBJECTS =  netstring_pcre.cmo
DOBJECTS = netstring_pcre.mli

include $(TOP_DIR)/Makefile.rules

REQUIRES += pcre

include depend
